[MAD] Improve our landing page and add a platform intro page
memfault/memfault-docs pull request #200
Opened 2022-04-12 16:56 UTC by fnune

See my [MAD project page on Notion][1].

[1]: https://www.notion.so/memfault/Docs-landing-page-draft-c2897dc6703f4f1c8e5459c9a7f40e09

2022-04-12 17:36 UTC, franc0is requested changes
Huge improvement!

I'd also like to change some of the navbar items:
- Rename "Platform" to "Dashboard"
- Add a link back to memfault.com 
- Ideally collapse "Linux/MCU/Android" into a dropdown menu called "Platforms"
- Rename Embedded Linux to Linux

2022-04-12 17:36 UTC, franc0is commented on src/pages/index.js
> +                                        Sample integration on an nRF9160 board
Rename to "Memfault Module in the nRF connect SDK"

2022-04-12 17:36 UTC, franc0is commented on src/pages/index.js
> +                                    <a href="https://developer.nordicsemi.com/nRF_Connect_SDK/doc/1.8.0/nrf/samples/nrf9160/memfault/README.html#memfault-sample">
Change link to point to latest:
https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/samples/nrf9160/memfault/README.html

2022-04-12 17:36 UTC, franc0is commented on src/pages/index.js
> +                            <p>Integration Guides</p>
Rename to "Getting Started"

2022-04-12 17:36 UTC, franc0is commented on src/pages/index.js
> +                                        MCU integration guide
Could consider adding icons / images to the links for the three platforms

2022-04-12 17:36 UTC, franc0is commented on src/pages/index.js
> +                            <p>Source Code</p>
Rename this to:
"Software Development Kits"
or
"Get the Code"

2022-04-12 17:36 UTC, franc0is commented on src/pages/index.js
> +                                </li>
Add two more:
"Memfault Bridge SDK for iOS" https://github.com/memfault/memfault-ios-cloud
"Memfault Bridge SDK for Android" https://github.com/memfault/memfault-cloud-android

2022-04-12 17:36 UTC, franc0is commented on src/pages/index.js
> +                                    </a>
Add another
[Memfault WebBluetooth Bridge](https://mflt.io/mds) ([docs](https://docs.memfault.com/docs/mcu/da1469x-sdk-guide/#post-data-to-cloud-via-web-bluetooth))

2022-04-12 17:36 UTC, franc0is commented on src/pages/index.js
> +                                    </a>
FWIW @chrisc11 I would prefer if this pointed to a Github page under the Memfault org rather than your own.

2022-04-13 12:09 UTC, HBehrens reviewed
Looks soooo much better – thank you! A couple of remarks (including seemingly wrong links or missing content)

2022-04-13 12:09 UTC, HBehrens commented on src/pages/index.js
> +                                        API reference
I am suggesting a rename from "API" to "REST API". This is to avoid confusion when enumerating this item next to our platforms which each have some APIs by themselves.

* This rename should also happen in the top navigation bar, I believe.
* Yes, we may not strictly speaking use REST everywhere but then again, our Postman page calls them "REST" themselves already

2022-04-13 12:09 UTC, HBehrens commented on src/pages/index.js
> +                                        <FiExternalLink />
I like how this is a different icon!

2022-04-13 12:09 UTC, HBehrens commented on src/pages/index.js
> +                                        <FiTerminal />
I love the icon!

2022-04-13 12:09 UTC, HBehrens commented on src/pages/index.js
> +                                    <a href="/docs/platform/introduction">
leads to an empty page

2022-04-13 12:09 UTC, HBehrens commented on src/pages/index.js
> +                                <li>
Should this item come first to match the order we use in other places? Also, should we call it "Web Application"?

2022-04-13 12:09 UTC, HBehrens commented on src/pages/index.js
> +                                    Memfault: End-to-End Firmware Management
I'd call out that this is a very brief intro video, how about "Quick introduction to Memfault"?

2022-04-13 12:09 UTC, HBehrens commented on src/pages/index.js
> +                        <h3>Videos</h3>
These videos greatly vary in length. Does it make sense to add their respective durations in the title? e.g.

* Quick Introduction to Memfault (2:16)
* Getting Started with Memfault for MCUs (50:46)
* Managing Android Devices At Scale with Memfault (58:54)

2022-04-13 12:10 UTC, fnune commented on src/pages/index.js
> +                        href="/docs/platform/introduction"
Yep, working on it!

I should probably remove the `Feature Overview` link for now and work on that page separately.

2022-04-13 12:11 UTC, noahp commented on src/pages/index.js
> +                                    <a href="https://developer.nordicsemi.com/nRF_Connect_SDK/doc/1.8.0/nrf/samples/nrf9160/memfault/README.html#memfault-sample">
We should probably keep these pinned to a specific version; they've been in the past

2022-04-13 12:11 UTC, fnune commented on src/pages/index.js
> +                                    <a href="/docs/platform/introduction">
https://github.com/memfault/memfault-docs/pull/200#discussion_r849409414

2022-04-13 12:11 UTC, fnune commented on src/pages/index.js
> +                                <li>
Yah Web Application sounds better.

2022-04-13 12:11 UTC, fnune commented on src/pages/index.js
> +                        <h3>Videos</h3>
Good idea!

2022-04-13 12:13 UTC, fnune commented on src/pages/index.js
> +                                    <a href="https://developer.nordicsemi.com/nRF_Connect_SDK/doc/1.8.0/nrf/samples/nrf9160/memfault/README.html#memfault-sample">
Both tips seem good but conflicting. Could we ask them if they have a permalink?

2022-04-13 12:13 UTC, fnune commented on src/pages/index.js
> +                                        MCU integration guide
This PR introduces `react-icons` into the docs. I'll see if they have something :+1:

2022-04-13 14:33 UTC, fnune commented on src/pages/index.js
> +                                    <a href="https://developer.nordicsemi.com/nRF_Connect_SDK/doc/1.8.0/nrf/samples/nrf9160/memfault/README.html#memfault-sample">
For now, resorting to pinning to the latest version `https://developer.nordicsemi.com/nRF_Connect_SDK/doc/1.9.1/nrf/samples/nrf9160/memfault/README.html`

2022-04-13 14:36 UTC, fnune commented on src/pages/index.js
> +                                    </a>
Resorting to linking to the docs for now, which also include the webapp link.

2022-04-13 14:38 UTC, fnune commented on src/pages/index.js
> +                        firmware issues and deploy OTA updates to your fleet.
:+1: never liked it, but it _is_ the more common style in the USA I feel?

2022-04-13 14:48 UTC, fnune commented on src/pages/index.js
> +                                        MCU integration guide
![image](https://user-images.githubusercontent.com/16181067/163207445-c9b44fa0-c5cf-47f1-a0aa-0db2778e4601.png)

:smile:

2022-04-13 15:08 UTC, merged

2022-04-13 15:08 UTC, fnune commented
Merging without the `Feature Overview` link and working on that page on another PR! Thanks for the thoughtful comments <3