MFLT-7553 Document debug data recordings feature
memfault/memfault-docs pull request #331
Opened 2022-11-04 09:36 UTC by SionAbes

MFLT-7553 Document debug data recordings feature

Adds information on Custom Data Recordings

<img width="1369" alt="Screenshot 2022-11-04 at 10 35 23" src="https://user-images.githubusercontent.com/60614083/199940670-a217988d-25a8-42bd-a4b1-6c7258c74a86.png">

<img width="1137" alt="Screenshot 2022-11-04 at 10 35 45" src="https://user-images.githubusercontent.com/60614083/199940738-b5883250-f399-4a7f-9d81-cf12448a4943.png">

Signed-off-by: SionAbes <sion.n.abraham@gmail.com>

2022-11-04 09:41 UTC, SionAbes commented
This is missing the CLI updates.

2022-11-04 10:24 UTC, martijnthe requested changes

2022-11-04 10:24 UTC, martijnthe commented on docs/platform/inspecting-a-device.mdx
> +![Screenshot showing basic custom data recording use case](/img/docs/platform/custom-data-recording.png)
Feedback on the screenshot:

- I would select the 3rd or 4rd, not the 1st. I think if there a a few blue pills shown before and after the popover, I think it's a bit easier to parse what's going on, visually.
- Maybe ensure that there's a bit of whitespace at the bottom? It's cropped a bit oddly now.

2022-11-04 10:24 UTC, martijnthe commented on docs/platform/inspecting-a-device.mdx
> +  custom data but the device needs to produce lines of text ahead of time.
When I read this, I was wondering "why do we need to tell this here?"
I don't think it's necessary to provide such detailed overview here.

To set the stage for the next paragraph, I do think it makes sense to say that Memfault collects various types of data out of the box (and give a few examples) and as a segue to saying the platform also supports collecting arbitrary data.

2022-11-04 10:24 UTC, martijnthe commented on docs/platform/inspecting-a-device.mdx
> +device. Data sent via Custom Data Recordings are of user defined file types and
- high-density telematic insights => this is an example, but CDR is not limited to that
- file => I would avoid the word "file" and instead use "data". File suggests things like one needs to have a file (MCU systems may not have a filesystem at all, but the API can still be used).

```suggestion
to collect custom data to specific events happening on your
device. Data sent via the Custom Data Recordings API can be of any format.
```

2022-11-04 10:24 UTC, martijnthe commented on docs/platform/inspecting-a-device.mdx
> +
I think we need explanation about the "metadata" of a CDR:
- reason
- mimetypes
- duration
- start_time

2022-11-04 10:24 UTC, martijnthe commented on docs/platform/inspecting-a-device.mdx
> +are parsed, visualised, and downloadable from the Device Timeline.
I'd leave out "parsed" until mimetypes is explained later on.

```suggestion
The Custom Data Recordings visualized on and downloadable from the Device Timeline.
```

2022-11-04 10:24 UTC, martijnthe commented on docs/platform/rate-limiting.mdx
> +        <Link to="https://docs.memfault.com/docs/platform/inspecting-a-device/##custom-data-recordings">
Need to use site-relative links (see examples of `<Link to="..." />` elsewhere).

Why the double `##`? Typo?

```suggestion
        <Link to="/docs/platform/inspecting-a-device/#custom-data-recordings">
```

2022-11-04 10:24 UTC, martijnthe commented on docs/platform/rate-limiting.mdx
> +        <Link to="https://docs.memfault.com/docs/platform/introduction/#device-metrics">
```suggestion
        <Link to="/docs/platform/introduction/#device-metrics">
```

2022-11-04 10:28 UTC, martijnthe commented on docs/platform/inspecting-a-device.mdx
> +
Here's a piece of docstring that Chris wrote that you could also use for inspiration:
https://github.com/memfault/memfault/pull/7904/files#diff-4a0784c80612758f8262a2afb06f8f6a5f25a33e58f77d418ca06721b290bae9R6-R10

2022-11-04 11:36 UTC, vlindhol reviewed
Lots of nits, mainly :) Leaving the final approval to Heiko!

2022-11-04 11:36 UTC, vlindhol commented on docs/platform/inspecting-a-device.mdx
> +when debugging issue (i.e trace data, proprietary coredumps, logs). Memfault
```suggestion
when debugging issues, for example trace data, proprietary coredumps, logs. Memfault
```

I remember being asked to remove "i.e.", "e.g." and so on, keeping the tradition going ;)

2022-11-04 11:36 UTC, vlindhol commented on docs/platform/inspecting-a-device.mdx
> +CDRs allow you to collect custom data to specific events happening on your
```suggestion
CDRs allow you to collect custom data for specific events happening on your
```

2022-11-04 11:36 UTC, vlindhol commented on docs/platform/inspecting-a-device.mdx
> +- **Mimetypes** - A list of MIME types, in descending order of specificity.
```suggestion
- **MIME type** - One or more MIME types describing the contents of the CDR.
```

2022-11-04 11:36 UTC, vlindhol commented on docs/platform/inspecting-a-device.mdx
> +  Decides how the CDR is visualized in the timeline.
```suggestion
```

Since we have 0 visualizers so far, no need to raise expectations :D

2022-11-04 11:36 UTC, vlindhol commented on docs/platform/inspecting-a-device.mdx
> +
General question for the metadata list below: do we in this document need to mention "validation details" like `limited to 100 unique values` or the units? Feels like here we should be talking more about the concepts rather than technical details.

2022-11-04 11:36 UTC, vlindhol commented on docs/platform/inspecting-a-device.mdx
> +represented with a bar or dot respectively. Clicking or hovering over a timeline
Dots may be going away, perhaps best not to mention UI details so specifically. Shouldn't be too hard to grok this particular part of the UI!

```suggestion
Clicking or hovering over a timeline
```

2022-11-04 12:00 UTC, martijnthe commented on docs/platform/inspecting-a-device.mdx
> +
Hmm, I think I would prefer to have limits also be described here. 

I can also see the "Rate Limiting" page grew into a more generic "Limits" page. [Heroku](https://devcenter.heroku.com/articles/limits) and [AWS](https://docs.aws.amazon.com/general/latest/gr/aws-service-information.html) take this approach.

But as a consumer of the docs, I personally would prefer having limits be described "in context".

@HBehrens or @tyhoff WDYT?

2022-11-04 12:06 UTC, martijnthe commented on docs/platform/inspecting-a-device.mdx
> +- **Mimetypes** - A list of MIME types, in descending order of specificity.
The order piece is important too though, I would keep that part in. Maybe as a separate sentence to make it easier to read.

2022-11-04 12:07 UTC, martijnthe commented on docs/platform/inspecting-a-device.mdx
> +  Decides how the CDR is visualized in the timeline.
I think it's OK to say the intention is to add visualizers in the future and that the mime types will be used to select the most-apt visualizer for the data.

2022-11-04 12:15 UTC, SionAbes commented on docs/platform/inspecting-a-device.mdx
> +CDRs allow you to collect custom data to specific events happening on your
[Welshisms](https://en.wikipedia.org/wiki/Colloquial_Welsh_prepositions)..

2022-11-04 12:18 UTC, martijnthe commented on docs/platform/inspecting-a-device.mdx
> +  time in UTC.
Need to mention it is optional. When not provided, the time of ingestion in the Memfault cloud will be used as fall-back.

2022-11-04 12:21 UTC, martijnthe commented on docs/platform/inspecting-a-device.mdx
> +- **Duration** - The time in seconds in which the CDR was captured over.
I would not mention "seconds" here, because this depends a bit on the API.
When one is using the HTTP API or memfault CLI, it's indeed seconds (floating point), but when using the [MCU API, it will be milliseconds (integer)](https://github.com/memfault/memfault/pull/7904/files#diff-4a0784c80612758f8262a2afb06f8f6a5f25a33e58f77d418ca06721b290bae9R65).

2022-11-04 14:57 UTC, HBehrens reviewed
Some minor suggestions + proposal to provide an example to guide the user ('s expectations) on best use of this feature.

2022-11-04 14:57 UTC, HBehrens commented on docs/ci/install-memfault-cli.mdx
> +  upload-coredump               Upload an MCU coredump for analysis.
nit: (and also not introduced in this PR) I noticed that the highlighter is configured as `bash` which seems to effect the output. I see `file` and `for` in a different color here. Does it make sense to change the highlighter to plain text?

![CleanShot 2022-11-04 at 15 33 59](https://user-images.githubusercontent.com/486904/200000921-fd9ddb73-cb40-4084-9374-56874a76e342.png)

2022-11-04 14:57 UTC, HBehrens commented on docs/platform/inspecting-a-device.mdx
> +Many projects have custom data formats which can be useful to analyze when
```suggestion
In some projects, devices already capture additional data in custom formats which can be useful to analyze when
```

2022-11-04 14:57 UTC, HBehrens commented on docs/platform/inspecting-a-device.mdx
> +device. Data sent via the CDR API can be of any format, which are then
```suggestion
device. Data sent via the CDR API can be of any format, which is then
```

2022-11-04 14:57 UTC, HBehrens commented on docs/platform/inspecting-a-device.mdx
> +bundled with extra metadata:
```suggestion
visualized and downloadable from the Device Timeline. To enable this, each CDR is
bundled with metadata when uploaded:
```

2022-11-04 14:57 UTC, HBehrens commented on docs/platform/inspecting-a-device.mdx
> +
Ideally, this limitation will be expressed at the API level (e.g. in C the SDK expresses this as a char array with fixed size). Instead of calling out explicit max-sizes here, I'd rather provide an example to the expected use. This will more softly familiarize them with the idea that reason is meant to be short and generic rather than long and with per-incident details.

2022-11-04 14:57 UTC, HBehrens commented on docs/platform/inspecting-a-device.mdx
> +- **MIME type** - One or more MIME types describing the contents of the CDR.
Does it make sense to to link to MDN here?

2022-11-04 14:57 UTC, HBehrens commented on docs/platform/inspecting-a-device.mdx
> +
Here: I would provide an example. Goals:
* Teach about reason and how we want id to be used.
* Teach how to use several MIME types with most-specific one first
* Teach about vendor-specific MIME types
* Show an example that makes them re-think if their use-case really doesn't have a duration.

2022-11-04 14:57 UTC, HBehrens commented on docs/platform/inspecting-a-device.mdx
> +![Screenshot showing basic custom data recording use case](/img/docs/platform/custom-data-recording.png)
The relevant piece of UI is very small on this screenshot. Can you re-align it to make better use of the screen estate?

2022-11-04 14:57 UTC, HBehrens commented on docs/platform/inspecting-a-device.mdx
> +![Screenshot showing basic custom data recording use case](/img/docs/platform/custom-data-recording.png)
Also: It's not immediately clear to me what one would download in the event of a device shutdown 🤔

2022-11-04 14:57 UTC, HBehrens commented on docs/platform/inspecting-a-device.mdx
> +the file for future analysis.
I think it makes sense to call out that CDRs are subject to rate limiting and link to the respective section on that page

2022-11-04 14:57 UTC, HBehrens commented on docs/platform/rate-limiting.mdx
> +          Custom Data Recordings{" "}
```suggestion
          Custom Data Recordings (CDR){" "}
```

2022-11-04 14:57 UTC, HBehrens commented on docs/platform/rate-limiting.mdx
> +        are sets of user defined data files of a specific type that are sent from
```suggestion
        are sets of user defined data of any custom format that are sent from
```
Let's not use the term "file" in the context of CDR

2022-11-04 14:57 UTC, HBehrens commented on docs/platform/inspecting-a-device.mdx
> +the file for future analysis.
```suggestion
the data for further analysis.
```
Let's avoid the term "file" in the context of CDR

2022-11-04 14:57 UTC, HBehrens commented on docs/platform/rate-limiting.mdx
> +        </Link>
Does that link make sense here? Since you already linked to the CDR section of the docs before, should we just remove that entire sentence?

2022-11-04 14:57 UTC, HBehrens commented on docs/platform/rate-limiting.mdx
> +    <tr id="custom-data-recordings-reasons">
```suggestion
    <tr id="custom-data-recordings">
```

2022-11-07 19:48 UTC, tyhoff commented on docs/platform/inspecting-a-device.mdx
> +which can be useful to analyze when debugging issues, for example trace data,
```suggestion
which can be useful to analyze when debugging issues, for example, trace data,
```

2022-11-08 09:43 UTC, martijnthe commented on docs/platform/inspecting-a-device.mdx
> +within propitiatory file, that you'd like to extract during high load
```suggestion
within proprietary file, that you'd like to extract during high load
```

2022-11-08 09:43 UTC, martijnthe commented on docs/platform/inspecting-a-device.mdx
> +visualization technique, where vendor specific MIME types might not be
```suggestion
visualization on the Device Timeline, where vendor specific MIME types might not be
```

2022-11-08 09:43 UTC, martijnthe commented on docs/platform/inspecting-a-device.mdx
> +
@SionAbes is it OK with you if I would take a stab at writing these examples that @HBehrens is asking for?
I can carve out some time tomorrow to do that.

2022-11-11 11:02 UTC, martijnthe commented on docs/platform/inspecting-a-device.mdx
> +![Screenshot showing basic custom data recording use case](/img/docs/platform/custom-data-recording.png)
I updated the screenshot from what's on master and with @SionAbes 's new demo data.

2022-11-11 11:34 UTC, SionAbes commented on docs/platform/inspecting-a-device.mdx
> +- adding test reports for devices in a hardware-in-the-loop test set up.
Nit: I would capitalise these, and remove the comma at the end!

2022-11-14 08:12 UTC, martijnthe approved these changes
Let's wait for @HBehrens final review before merging this.

2022-11-14 08:22 UTC, HBehrens commented
Thank y'all – will review this morning.

2022-11-16 07:48 UTC, martijnthe commented
> Thank y'all – will review this morning.

@HBehrens gentle poke ;)

2022-11-29 11:09 UTC, HBehrens approved these changes
LGTM. A few very minor remarks and suggestions.

2022-11-29 11:09 UTC, HBehrens commented on docs/platform/inspecting-a-device.mdx
> +"enum" and use only a small set of static values. In the Device Timeline, all
```suggestion
"enum" and to use and re-use only a small set of static values. In the Device Timeline, all
```

2022-11-29 11:09 UTC, HBehrens commented on docs/platform/inspecting-a-device.mdx
> +for devices having CDRs with a given (set of) reasons.
While we generally try to avoid talking about future functionality, I'd say we leave it here as it may help customers to understand how to best choose the reason string.

2022-11-29 11:09 UTC, HBehrens commented on docs/platform/inspecting-a-device.mdx
> +We recommend using one of the types in the
```suggestion
When using proprietary MIME types, we recommend using one of the types in the
```

2022-11-29 11:09 UTC, HBehrens commented on docs/platform/inspecting-a-device.mdx
> +in the future. For this reason, we recommended using an accurate list of MIME
```suggestion
in the future. It also helps identifying the format of the payload when downloading it from the device timeline. For this reason, we recommended using an accurate list of MIME
```

2022-11-29 11:09 UTC, HBehrens commented on docs/platform/inspecting-a-device.mdx
> +<h3 id="cdr-reason">CDR Reason</h3>
nit (here and throughout the doc): Docusaurus understand IDs in markdown https://docusaurus.io/docs/next/markdown-features/toc#heading-ids

2022-11-29 11:09 UTC, HBehrens commented on docs/platform/inspecting-a-device.mdx
> +| `application/octet-stream`     | Binary data | Coming soon: a preview of the contents in a hex viewer in the popover of the CDR. |
Again, we usually try to avoid announcing future features in our docs but we keep it here to inform how to use our mandatory field MIME type.

2022-11-29 11:22 UTC, merged